# Generated by Django 3.1.2 on 2020-11-01 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dotgames', '0003_auto_20201101_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
