# Generated by Django 3.1.2 on 2020-11-29 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dotgames', '0007_juego_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
