# Generated by Django 3.1.2 on 2020-11-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotgames', '0008_auto_20201129_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='genero',
        ),
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dotgames.genero'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
