# Generated by Django 3.1.2 on 2020-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotgames', '0010_auto_20201129_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(help_text='Descripción del autor', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(default='dotgames/static/img/no.png', upload_to='dotgames'),
        ),
        migrations.AddField(
            model_name='autor',
            name='sexo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
